channels:
- defaults
- conda-forge
dependencies:
- bandit==1.6.2
- GitPython==3.1.3
- gitdb==4.0.5
- smmap==3.0.4
- stevedore==3.2.2
- pbr==5.5.0
- flake8==3.8.3
- mccabe==0.6.1
- pycodestyle==2.6.0
- pyflakes==2.2.0
- flake8-black==0.2.1
- black==19.10b0
- appdirs==1.4.4
- attrs==20.1.0
- click==7.1.2
- pathspec==0.7.0
- regex==2020.7.14
- toml==0.10.1
- typed-ast==1.4.1
- flake8-docstrings==1.5.0
- pydocstyle==5.1.1
- snowballstemmer==2.0.0
- flake8-isort==3.0.1
- isort==4.3.21
- testfixtures==6.14.1
- pip:
  - flake8-bandit==2.1.2
  - flake8-polyfill==1.0.2
